### PR TITLE
[feat] ✨ add issue & PR template

### PR DESCRIPTION
**Pull request by anuraglol**
This PR closes #7

### CODE REVIEW

**Review by akhileshthite — COMMENTED** [review]
I need standard templates,
username and type is not necessary. Please check out issue and PR templates of other projects, use the most common ones. Make changes accordingly.

**Comment by anuraglol** [comment]
hey
i have done some changes, lemme know about your review

**Comment by akhileshthite** [comment]
> hey i have done some changes, lemme know about your review

You can copy-paste this:
https://github.com/AkhileshThite/covid19-vaccine-finder/tree/main/.github/ISSUE_TEMPLATE

**Comment by anuraglol** [comment]
> > hey i have done some changes, lemme know about your review
> 
> You can copy-paste this: https://github.com/AkhileshThite/covid19-vaccine-finder/tree/main/.github/ISSUE_TEMPLATE

ah okey, and are you satisfied by the PR template btw?

**Comment by akhileshthite** [comment]
> > > hey i have done some changes, lemme know about your review
> > 
> > 
> > You can copy-paste this: https://github.com/AkhileshThite/covid19-vaccine-finder/tree/main/.github/ISSUE_TEMPLATE
> 
> ah okey, and are you satisfied by the PR template btw?

Good. Will merge tomorrow.

**Comment by anuraglol** [comment]
> > > > hey i have done some changes, lemme know about your review
> > > 
> > > 
> > > You can copy-paste this: https://github.com/AkhileshThite/covid19-vaccine-finder/tree/main/.github/ISSUE_TEMPLATE
> > 
> > 
> > ah okey, and are you satisfied by the PR template btw?
> 
> Good. Will merge tomorrow.

okay, thanks!

**Comment by akhileshthite** [comment]
> > > > > hey i have done some changes, lemme know about your review
> > > > 
> > > > 
> > > > You can copy-paste this: https://github.com/AkhileshThite/covid19-vaccine-finder/tree/main/.github/ISSUE_TEMPLATE
> > > 
> > > 
> > > ah okey, and are you satisfied by the PR template btw?
> > 
> > 
> > Good. Will merge tomorrow.
> 
> okay, thanks!

Can you change the PR template, sorry it's small and doesn't match with issue template. Add from this link.
https://github.com/AkhileshThite/covid19-vaccine-finder/blob/main/.github/PR_TEMPLATE.md

**Comment by akhileshthite** [comment]
You can use these in the future, hope you learned something. Good work 👍
Also don't use "Added" past tense for commits, use "Add" imperative. Keep that in mind.

**Comment by anuraglol** [comment]
> You can use these in the future, hope you learned something. Good work 👍 Also don't use "Added" past tense for commits, use "Add" imperative. Keep that in mind.

ah, thanks for the suggestion! will keep these in mind, Thanks!

**Comment by akhileshthite** [comment]
> > > > > > hey i have done some changes, lemme know about your review
> > > > > 
> > > > > 
> > > > > You can copy-paste this: https://github.com/AkhileshThite/covid19-vaccine-finder/tree/main/.github/ISSUE_TEMPLATE
> > > > 
> > > > 
> > > > ah okey, and are you satisfied by the PR template btw?
> > > 
> > > 
> > > Good. Will merge tomorrow.
> > 
> > 
> > okay, thanks!
> 
> Can you change the PR template, sorry it's small and doesn't match with issue template. Add from this link. https://github.com/AkhileshThite/covid19-vaccine-finder/blob/main/.github/PR_TEMPLATE.md

Please make this change so that i can merge your PR :)

**Comment by anuraglol** [comment]
> > > > > > > hey i have done some changes, lemme know about your review
> > > > > > 
> > > > > > 
> > > > > > You can copy-paste this: https://github.com/AkhileshThite/covid19-vaccine-finder/tree/main/.github/ISSUE_TEMPLATE
> > > > > 
> > > > > 
> > > > > ah okey, and are you satisfied by the PR template btw?
> > > > 
> > > > 
> > > > Good. Will merge tomorrow.
> > > 
> > > 
> > > okay, thanks!
> > 
> > 
> > Can you change the PR template, sorry it's small and doesn't match with issue template. Add from this link. https://github.com/AkhileshThite/covid19-vaccine-finder/blob/main/.github/PR_TEMPLATE.md
> 
> Please make this change so that i can merge your PR :)

ah, okey, lemme do it

**Review by akhileshthite — APPROVED** [review]

**Pull request merged**
