### PR TITLE
Split qrcode.js into 3 files: qrHandler.js, utils.js, and web3Storage.js

### LINKED ISSUE #40: refactor: split qrcode script in several files for maintainability
Please break down the `qrcode.js` file into several files for better maintainability.

These files should be:
- ./src/scripts/`web3Storage.js`
- ./src/scripts/`qrHandler.js`
- ./src/scripts/`utils.js`

The file `qrcode.js` is already organized into these sections. However, please ensure you import and export all necessary functions and variables.

> ⚠️ Important: To avoid listeners being called multiple times, ensure they are set only once. You can wrap the listeners in a function and ensure that this function is called just once (or adopt any other solution you prefer).

Source:
[./src/scripts/qrcode.js](https://github.com/p2plabsxyz/dscan/blob/main/src/scripts/qrcode.js)
[./webpack.config.js](https://github.com/p2plabsxyz/dscan/blob/main/webpack.config.js)

> For development setup and contribution guide, check the main [README.md](https://github.com/buidltools/dscan).

### PR DESCRIPTION
**Pull request by AdityaNik**
## Related Issue (if any)

Closes: #40 

### Describe the add-ons or changes you've made

In this Pull Request, I've split the existing `qrcode.js` file into three separate files: `qrHandler.js`, `utils.js`, and `web3Storage.js`. 

## Type of change

- [x] Refractor (Splitting up the files)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the "contribution guidelines" of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by AdityaNik** [comment]
@akhileshthite please review

**Comment by akhileshthite** [comment]
> @akhileshthite please review

Thanks!
Looks good to me.

Will merge tomorrow.

**Review by akhileshthite — APPROVED** [review]

**Comment by akhileshthite** [comment]
@AdityaNik, merged. Great work!
There's another active issue if you're interested #41

**Comment by AdityaNik** [comment]
@akhileshthite looking forward to solve that as well

**Comment by akhileshthite** [comment]
> @akhileshthite looking forward to solve that as well

Cool, let me know when you start the work so I can assign the issue to you.

**Pull request merged**
