### PR TITLE
 [bug]: file and folder buttons not clicking properly #17

### PR DESCRIPTION
**Pull request by atifcppprogrammer**
The following video illustrates the results of the following changes
<div align="center">
<video src="https://user-images.githubusercontent.com/54069350/158059076-13105148-488b-4152-964a-8666e0e8f67c.mp4">
</video>
</div>

### CODE REVIEW

**Comment by akhileshthite** [comment]
> The following video illustrates the results of the following changes
> 
>  changes.mp4

@atifcppprogrammer Nope, the active one should look "pressed" as before, only the "slight bounce should be fixed", otherwise the user cannot understand what they're uploading. We don't want bad UX :)

Just updated the issue so there should be no confusion.

**Comment by atifcppprogrammer** [comment]
Thanks @AkhileshThite i'll take a look at it again.

**Comment by atifcppprogrammer** [comment]
Hey @AkhileshThite i think this one is resolved please see the following.


https://user-images.githubusercontent.com/54069350/158071692-4bf9d526-1b92-4901-98b5-4f6376f934fc.mp4

**Comment by akhileshthite** [comment]
> Hey @AkhileshThite i think this one is resolved please see the following.
> 
>  changes.mp4

Good, I'll test and merge in 2-3 days.

**Review by akhileshthite — APPROVED** [review]

**Pull request merged**
