### PR TITLE
[bug]: loader spinning on the generated QR code #14

### PR DESCRIPTION
**Pull request by atifcppprogrammer**
- ensured that QRCode appers once CID is received.
- used JQuery's .off() so that one listener is attached.
- changed DOM selector to download generated QRCode.
- refactored code a bit to prevent code duplication.

### CODE REVIEW

**Review by akhileshthite — APPROVED** [review]

**Comment by AkhileshThite** [comment]
@atifcppprogrammer 
Great work!

**Comment by atifcppprogrammer** [comment]
Thanks @AkhileshThite I don't think that will be necessary since I am already watching the project.

**Comment by atifcppprogrammer** [comment]
Thanks @AkhileshThite I don't think that will be necessary since I am already watching the project.

**Comment by AkhileshThite** [comment]
> Thanks @AkhileshThite I don't think that will be necessary since I am already watching the project, here on GitHub.

Sure, np.

**Pull request merged**
