### PR TITLE
feature: colour customisation for QR codes

### LINKED ISSUE #29: feat: colour customisation for QR codes
A colour bar or an input box appears with QR code for customisations.

Screenshot 2022-10-07 at 2 30 11 PM

### Files:

Colour input:
https://github.com/buidltools/dscan/blob/adaa07878bfef9216f43e0656736e4570af68593/src/js/qrcode.js#L12

`HTML`:
For file: https://github.com/buidltools/dscan/blob/main/src/popup.html
For folder: https://github.com/buidltools/dscan/blob/main/src/folderUpload.html

`CSS`: https://github.com/buidltools/dscan/blob/main/src/css/popup.css

`JS`: https://github.com/buidltools/dscan/blob/main/src/js/qrcode.js

For `development setup` and `contribution guide`, check the main [README.md](https://github.com/buidltools/dscan).

### PR DESCRIPTION
**Pull request by g1mishra**
## Related Issue (if any)

Closes: #29 

### Describe the add-ons or changes you've made

Added an input type="color" as color picker. On color change event clearing the QR code, setting the color value, and 
re-drawing the QR code.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
It was tested by uploading various files and folders.

A new color picker was visible beside the QR code and working fine.

## Checklist:

- [x] My code follows the "contribution guidelines" of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots (Only for Front End and UI/UX Designers)

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Review by akhileshthite — APPROVED** [review]
🤟

**Comment by g1mishra** [comment]
@akhileshthite can you please add the “hacktoberfest-accepted” label?

**Comment by akhileshthite** [comment]
> @akhileshthite can you please add the “hacktoberfest-accepted” label?

They didn't mention anything specific this time.
Screenshot 2022-10-08 at 8 46 10 PM

Can you refresh your hacktoberfest dashboard? 
If they're not counting this PR then let me know, I'll add `hacktoberfest-accepted` label.

**Comment by g1mishra** [comment]
Okay cool, thanks 👍🏻

**Pull request merged**
